### ISSUE TITLE
Appointment status update fails if primary performer is not available when appointment is scheduled.

### ISSUE THREAD

**Issue by satishjayakumar** [GEHealthcare/apiserver.gehealthcare.com#274] opened 2023-04-25 03:11 UTC
We have an appointment that was created in athenaPractice without a Resp. Provider/ primary performer. 
When we try to update this appointment with status as 'Booked' or 'Arrived' the API call is failing with the below error message.
We also tried to pass a valid Practitioner as part of primary performer, but we got the same error.

Error Message :
"issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: java.lang.NullPointerException"
        }
    ]
![image](https://user-images.githubusercontent.com/9380111/234164879-bcba3b4c-7722-406b-9da6-99616f5747ef.png)

Attached the Request object - [AppointmentStatusUpdate.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/11316091/AppointmentStatusUpdate.txt)

**Comment by AjeetYadav07** [comment] 2023-05-17 12:36
Can you recreate the scenario on the ap22sandbox? we are trying to replicate this issue but no luck. if it is possible for you, please replicate the process to get more understanding for the same.

**Comment by Torin-Shepard-athena** [comment] 2023-05-18 17:50
@satishjayakumar We need more information from you to reproduce the issue.
The AppointmentStatusUpdate.txt file contained Appointment.id=1952.  This appointment is not found in ap22sandbox machine.

Can you perform this using our V22 API Sandbox machine?  Can you repeat your workflow using https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer so we can get current information written to the athenaPractice V22 Sandbox API Server log files?

Please describe how the appointment was created in athenaPractice without a Resp. Provider.
Did you create this through FHIR?  If so, please give us both the URL and request body for the POST request that created the appointment and the PUT request attempted to update the appointment.
If you did not create the appointment through FHIR, please give more details about how it was created.

**Comment by AjeetYadav07** [comment] 2023-10-25 07:55
@satishjayakumar,
Marking as closed, since waiting for the issue clarification which isn't provided yet. Please register the new issue, If you are having  any query.

**Closed as completed by AjeetYadav07** 2023-10-25 07:55 UTC
